# Dockerfile used to create "husyci/gitleaks" image
# https://hub.docker.com/r/horuszup/gitleaks/

FROM zricethezav/gitleaks

RUN apk --no-cache add ca-certificates openssh-client jq

ENTRYPOINT []
CMD ["/bin/sh"]