name: DeployCLITools

on:
  workflow_dispatch:
    inputs:
      tool_name:
        description: 'Tool name'
        required: true
      update_type:
        description: 'Update Type: alpha, rc, release, minor, major'
        required: true
      is_to_update_latest:
        description: 'Is to update latest: true, false'
        required: true

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: deploy
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          if [[ -z "$DOCKER_USERNAME" || -z "$DOCKER_PASSWORD" ]]
          then
              echo "Variables DOCKER_USERNAME, DOCKER_PASSWORD is required"
              exit 1
          fi
          UPDATE_TYPE="${{ github.event.inputs.update_type }}"
          IS_TO_UPDATE_LATEST="${{ github.event.inputs.is_to_update_latest }}"
          TOOL_NAME="${{ github.event.inputs.tool_name }}"
          BRANCH_NAME=${GITHUB_REF##*/}
          
          echo "$UPDATE_TYPE"
          echo "$IS_TO_UPDATE_LATEST"
          echo "$TOOL_NAME"
          echo "$BRANCH_NAME"
          
