name: Security

on: [push]

jobs:
  horus:
    name: horus
    runs-on: ubuntu-latest
    container: horuszup/horus-cli:v1.0.16-alpha.3
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Running Horus Security
      run: horus start -p ./
