name: SecurityPipeline

on: [push]

jobs:
  horusec-security:
    name: horusec-security
    runs-on: ubuntu-latest
    container: horuszup/horusec-cli
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: security
        run: sh /usr/local/bin/horusec-cli.sh -p="./" -e="true"
