name: Pipeline

on: [push]

jobs:
  security:
    name: security
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Running Horus
        run: |
          ls
          ./horus start -p="./"
