name: Security

on: [push]

jobs:
  horus:
    name: horus
    runs-on: ubuntu-latest
    container: horuszup/horus-cli:v1.0.16-alpha.4
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Running Horus Security
      run: |
        sleep 5
        docker ps -a
        horus start -p .
        docker ps -a
        docker image ls
