name: Pipeline

on: [push]

jobs:
  security:
    name: security
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Running Horus
        run: |
          curl -fsSL https://horus-assets.s3.amazonaws.com/horus | bash
          ./horus start -p="./"
